QT += core
QT -= gui

CONFIG += c++11

TARGET = TestMyAlgorithm
CONFIG += console
CONFIG -= app_bundle

TEMPLATE = app

SOURCES += main.cpp \
    test16binto16string.cpp \
    lib/Catch2/include/internal/benchmark/detail/catch_stats.cpp \
    lib/Catch2/include/internal/catch_approx.cpp \
    lib/Catch2/include/internal/catch_assertionhandler.cpp \
    lib/Catch2/include/internal/catch_assertionresult.cpp \
    lib/Catch2/include/internal/catch_capture_matchers.cpp \
    lib/Catch2/include/internal/catch_commandline.cpp \
    lib/Catch2/include/internal/catch_common.cpp \
    lib/Catch2/include/internal/catch_config.cpp \
    lib/Catch2/include/internal/catch_console_colour.cpp \
    lib/Catch2/include/internal/catch_context.cpp \
    lib/Catch2/include/internal/catch_debug_console.cpp \
    lib/Catch2/include/internal/catch_debugger.cpp \
    lib/Catch2/include/internal/catch_decomposer.cpp \
    lib/Catch2/include/internal/catch_enforce.cpp \
    lib/Catch2/include/internal/catch_enum_values_registry.cpp \
    lib/Catch2/include/internal/catch_errno_guard.cpp \
    lib/Catch2/include/internal/catch_exception_translator_registry.cpp \
    lib/Catch2/include/internal/catch_fatal_condition.cpp \
    lib/Catch2/include/internal/catch_generators.cpp \
    lib/Catch2/include/internal/catch_interfaces_capture.cpp \
    lib/Catch2/include/internal/catch_interfaces_config.cpp \
    lib/Catch2/include/internal/catch_interfaces_exception.cpp \
    lib/Catch2/include/internal/catch_interfaces_registry_hub.cpp \
    lib/Catch2/include/internal/catch_interfaces_reporter.cpp \
    lib/Catch2/include/internal/catch_interfaces_runner.cpp \
    lib/Catch2/include/internal/catch_interfaces_testcase.cpp \
    lib/Catch2/include/internal/catch_leak_detector.cpp \
    lib/Catch2/include/internal/catch_list.cpp \
    lib/Catch2/include/internal/catch_matchers.cpp \
    lib/Catch2/include/internal/catch_matchers_floating.cpp \
    lib/Catch2/include/internal/catch_matchers_generic.cpp \
    lib/Catch2/include/internal/catch_matchers_string.cpp \
    lib/Catch2/include/internal/catch_message.cpp \
    lib/Catch2/include/internal/catch_output_redirect.cpp \
    lib/Catch2/include/internal/catch_polyfills.cpp \
    lib/Catch2/include/internal/catch_random_number_generator.cpp \
    lib/Catch2/include/internal/catch_registry_hub.cpp \
    lib/Catch2/include/internal/catch_reporter_registry.cpp \
    lib/Catch2/include/internal/catch_result_type.cpp \
    lib/Catch2/include/internal/catch_run_context.cpp \
    lib/Catch2/include/internal/catch_section.cpp \
    lib/Catch2/include/internal/catch_section_info.cpp \
    lib/Catch2/include/internal/catch_session.cpp \
    lib/Catch2/include/internal/catch_singletons.cpp \
    lib/Catch2/include/internal/catch_startup_exception_registry.cpp \
    lib/Catch2/include/internal/catch_stream.cpp \
    lib/Catch2/include/internal/catch_string_manip.cpp \
    lib/Catch2/include/internal/catch_stringref.cpp \
    lib/Catch2/include/internal/catch_tag_alias.cpp \
    lib/Catch2/include/internal/catch_tag_alias_autoregistrar.cpp \
    lib/Catch2/include/internal/catch_tag_alias_registry.cpp \
    lib/Catch2/include/internal/catch_test_case_info.cpp \
    lib/Catch2/include/internal/catch_test_case_registry_impl.cpp \
    lib/Catch2/include/internal/catch_test_case_tracker.cpp \
    lib/Catch2/include/internal/catch_test_registry.cpp \
    lib/Catch2/include/internal/catch_test_spec.cpp \
    lib/Catch2/include/internal/catch_test_spec_parser.cpp \
    lib/Catch2/include/internal/catch_timer.cpp \
    lib/Catch2/include/internal/catch_tostring.cpp \
    lib/Catch2/include/internal/catch_totals.cpp \
    lib/Catch2/include/internal/catch_uncaught_exceptions.cpp \
    lib/Catch2/include/internal/catch_version.cpp \
    lib/Catch2/include/internal/catch_wildcard_pattern.cpp \
    lib/Catch2/include/internal/catch_xmlwriter.cpp \
    lib/Catch2/include/reporters/catch_reporter_bases.cpp \
    lib/Catch2/include/reporters/catch_reporter_compact.cpp \
    lib/Catch2/include/reporters/catch_reporter_console.cpp \
    lib/Catch2/include/reporters/catch_reporter_junit.cpp \
    lib/Catch2/include/reporters/catch_reporter_listening.cpp \
    lib/Catch2/include/reporters/catch_reporter_xml.cpp

INCLUDEPATH += lib/Catch2/include

HEADERS += \
    lib/Catch2/include/catch.hpp \
    lib/Catch2/include/catch_with_main.hpp \
    lib/Catch2/include/external/clara.hpp \
    lib/Catch2/include/internal/benchmark/detail/catch_analyse.hpp \
    lib/Catch2/include/internal/benchmark/detail/catch_benchmark_function.hpp \
    lib/Catch2/include/internal/benchmark/detail/catch_complete_invoke.hpp \
    lib/Catch2/include/internal/benchmark/detail/catch_estimate_clock.hpp \
    lib/Catch2/include/internal/benchmark/detail/catch_measure.hpp \
    lib/Catch2/include/internal/benchmark/detail/catch_repeat.hpp \
    lib/Catch2/include/internal/benchmark/detail/catch_run_for_at_least.hpp \
    lib/Catch2/include/internal/benchmark/detail/catch_stats.hpp \
    lib/Catch2/include/internal/benchmark/detail/catch_timing.hpp \
    lib/Catch2/include/internal/benchmark/catch_benchmark.hpp \
    lib/Catch2/include/internal/benchmark/catch_chronometer.hpp \
    lib/Catch2/include/internal/benchmark/catch_clock.hpp \
    lib/Catch2/include/internal/benchmark/catch_constructor.hpp \
    lib/Catch2/include/internal/benchmark/catch_environment.hpp \
    lib/Catch2/include/internal/benchmark/catch_estimate.hpp \
    lib/Catch2/include/internal/benchmark/catch_execution_plan.hpp \
    lib/Catch2/include/internal/benchmark/catch_optimizer.hpp \
    lib/Catch2/include/internal/benchmark/catch_outlier_classification.hpp \
    lib/Catch2/include/internal/benchmark/catch_sample_analysis.hpp \
    lib/Catch2/include/internal/catch_approx.h \
    lib/Catch2/include/internal/catch_assertionhandler.h \
    lib/Catch2/include/internal/catch_assertioninfo.h \
    lib/Catch2/include/internal/catch_assertionresult.h \
    lib/Catch2/include/internal/catch_capture.hpp \
    lib/Catch2/include/internal/catch_capture_matchers.h \
    lib/Catch2/include/internal/catch_clara.h \
    lib/Catch2/include/internal/catch_commandline.h \
    lib/Catch2/include/internal/catch_common.h \
    lib/Catch2/include/internal/catch_compiler_capabilities.h \
    lib/Catch2/include/internal/catch_config.hpp \
    lib/Catch2/include/internal/catch_console_colour.h \
    lib/Catch2/include/internal/catch_context.h \
    lib/Catch2/include/internal/catch_debug_console.h \
    lib/Catch2/include/internal/catch_debugger.h \
    lib/Catch2/include/internal/catch_decomposer.h \
    lib/Catch2/include/internal/catch_default_main.hpp \
    lib/Catch2/include/internal/catch_enforce.h \
    lib/Catch2/include/internal/catch_enum_values_registry.h \
    lib/Catch2/include/internal/catch_errno_guard.h \
    lib/Catch2/include/internal/catch_exception_translator_registry.h \
    lib/Catch2/include/internal/catch_external_interfaces.h \
    lib/Catch2/include/internal/catch_fatal_condition.h \
    lib/Catch2/include/internal/catch_generators.hpp \
    lib/Catch2/include/internal/catch_generators_generic.hpp \
    lib/Catch2/include/internal/catch_generators_specific.hpp \
    lib/Catch2/include/internal/catch_impl.hpp \
    lib/Catch2/include/internal/catch_interfaces_capture.h \
    lib/Catch2/include/internal/catch_interfaces_config.h \
    lib/Catch2/include/internal/catch_interfaces_enum_values_registry.h \
    lib/Catch2/include/internal/catch_interfaces_exception.h \
    lib/Catch2/include/internal/catch_interfaces_generatortracker.h \
    lib/Catch2/include/internal/catch_interfaces_registry_hub.h \
    lib/Catch2/include/internal/catch_interfaces_reporter.h \
    lib/Catch2/include/internal/catch_interfaces_runner.h \
    lib/Catch2/include/internal/catch_interfaces_tag_alias_registry.h \
    lib/Catch2/include/internal/catch_interfaces_testcase.h \
    lib/Catch2/include/internal/catch_leak_detector.h \
    lib/Catch2/include/internal/catch_list.h \
    lib/Catch2/include/internal/catch_matchers.h \
    lib/Catch2/include/internal/catch_matchers_floating.h \
    lib/Catch2/include/internal/catch_matchers_generic.hpp \
    lib/Catch2/include/internal/catch_matchers_string.h \
    lib/Catch2/include/internal/catch_matchers_vector.h \
    lib/Catch2/include/internal/catch_message.h \
    lib/Catch2/include/internal/catch_meta.hpp \
    lib/Catch2/include/internal/catch_objc.hpp \
    lib/Catch2/include/internal/catch_objc_arc.hpp \
    lib/Catch2/include/internal/catch_option.hpp \
    lib/Catch2/include/internal/catch_output_redirect.h \
    lib/Catch2/include/internal/catch_platform.h \
    lib/Catch2/include/internal/catch_polyfills.hpp \
    lib/Catch2/include/internal/catch_preprocessor.hpp \
    lib/Catch2/include/internal/catch_random_number_generator.h \
    lib/Catch2/include/internal/catch_reenable_warnings.h \
    lib/Catch2/include/internal/catch_reporter_registrars.hpp \
    lib/Catch2/include/internal/catch_reporter_registry.h \
    lib/Catch2/include/internal/catch_result_type.h \
    lib/Catch2/include/internal/catch_run_context.h \
    lib/Catch2/include/internal/catch_section.h \
    lib/Catch2/include/internal/catch_section_info.h \
    lib/Catch2/include/internal/catch_session.h \
    lib/Catch2/include/internal/catch_singletons.hpp \
    lib/Catch2/include/internal/catch_startup_exception_registry.h \
    lib/Catch2/include/internal/catch_stream.h \
    lib/Catch2/include/internal/catch_string_manip.h \
    lib/Catch2/include/internal/catch_stringref.h \
    lib/Catch2/include/internal/catch_suppress_warnings.h \
    lib/Catch2/include/internal/catch_tag_alias.h \
    lib/Catch2/include/internal/catch_tag_alias_autoregistrar.h \
    lib/Catch2/include/internal/catch_tag_alias_registry.h \
    lib/Catch2/include/internal/catch_test_case_info.h \
    lib/Catch2/include/internal/catch_test_case_registry_impl.h \
    lib/Catch2/include/internal/catch_test_case_tracker.h \
    lib/Catch2/include/internal/catch_test_registry.h \
    lib/Catch2/include/internal/catch_test_spec.h \
    lib/Catch2/include/internal/catch_test_spec_parser.h \
    lib/Catch2/include/internal/catch_text.h \
    lib/Catch2/include/internal/catch_timer.h \
    lib/Catch2/include/internal/catch_to_string.hpp \
    lib/Catch2/include/internal/catch_tostring.h \
    lib/Catch2/include/internal/catch_totals.h \
    lib/Catch2/include/internal/catch_type_traits.hpp \
    lib/Catch2/include/internal/catch_uncaught_exceptions.h \
    lib/Catch2/include/internal/catch_user_interfaces.h \
    lib/Catch2/include/internal/catch_version.h \
    lib/Catch2/include/internal/catch_wildcard_pattern.h \
    lib/Catch2/include/internal/catch_windows_h_proxy.h \
    lib/Catch2/include/internal/catch_xmlwriter.h \
    lib/Catch2/include/reporters/catch_reporter_automake.hpp \
    lib/Catch2/include/reporters/catch_reporter_bases.hpp \
    lib/Catch2/include/reporters/catch_reporter_compact.h \
    lib/Catch2/include/reporters/catch_reporter_console.h \
    lib/Catch2/include/reporters/catch_reporter_junit.h \
    lib/Catch2/include/reporters/catch_reporter_listening.h \
    lib/Catch2/include/reporters/catch_reporter_tap.hpp \
    lib/Catch2/include/reporters/catch_reporter_teamcity.hpp \
    lib/Catch2/include/reporters/catch_reporter_xml.h \
    lib/Crypto++/include/Cryptopp/3way.h \
    lib/Crypto++/include/Cryptopp/adler32.h \
    lib/Crypto++/include/Cryptopp/adv-simd.h \
    lib/Crypto++/include/Cryptopp/aes.h \
    lib/Crypto++/include/Cryptopp/algebra.h \
    lib/Crypto++/include/Cryptopp/algparam.h \
    lib/Crypto++/include/Cryptopp/arc4.h \
    lib/Crypto++/include/Cryptopp/argnames.h \
    lib/Crypto++/include/Cryptopp/aria.h \
    lib/Crypto++/include/Cryptopp/asn.h \
    lib/Crypto++/include/Cryptopp/authenc.h \
    lib/Crypto++/include/Cryptopp/base32.h \
    lib/Crypto++/include/Cryptopp/base64.h \
    lib/Crypto++/include/Cryptopp/basecode.h \
    lib/Crypto++/include/Cryptopp/bench.h \
    lib/Crypto++/include/Cryptopp/blake2.h \
    lib/Crypto++/include/Cryptopp/blowfish.h \
    lib/Crypto++/include/Cryptopp/blumshub.h \
    lib/Crypto++/include/Cryptopp/camellia.h \
    lib/Crypto++/include/Cryptopp/cast.h \
    lib/Crypto++/include/Cryptopp/cbcmac.h \
    lib/Crypto++/include/Cryptopp/ccm.h \
    lib/Crypto++/include/Cryptopp/chacha.h \
    lib/Crypto++/include/Cryptopp/channels.h \
    lib/Crypto++/include/Cryptopp/cmac.h \
    lib/Crypto++/include/Cryptopp/config.h \
    lib/Crypto++/include/Cryptopp/cpu.h \
    lib/Crypto++/include/Cryptopp/crc.h \
    lib/Crypto++/include/Cryptopp/cryptlib.h \
    lib/Crypto++/include/Cryptopp/default.h \
    lib/Crypto++/include/Cryptopp/des.h \
    lib/Crypto++/include/Cryptopp/dh.h \
    lib/Crypto++/include/Cryptopp/dh2.h \
    lib/Crypto++/include/Cryptopp/dll.h \
    lib/Crypto++/include/Cryptopp/dmac.h \
    lib/Crypto++/include/Cryptopp/drbg.h \
    lib/Crypto++/include/Cryptopp/dsa.h \
    lib/Crypto++/include/Cryptopp/eax.h \
    lib/Crypto++/include/Cryptopp/ec2n.h \
    lib/Crypto++/include/Cryptopp/eccrypto.h \
    lib/Crypto++/include/Cryptopp/ecp.h \
    lib/Crypto++/include/Cryptopp/ecpoint.h \
    lib/Crypto++/include/Cryptopp/elgamal.h \
    lib/Crypto++/include/Cryptopp/emsa2.h \
    lib/Crypto++/include/Cryptopp/eprecomp.h \
    lib/Crypto++/include/Cryptopp/esign.h \
    lib/Crypto++/include/Cryptopp/factory.h \
    lib/Crypto++/include/Cryptopp/fhmqv.h \
    lib/Crypto++/include/Cryptopp/files.h \
    lib/Crypto++/include/Cryptopp/filters.h \
    lib/Crypto++/include/Cryptopp/fips140.h \
    lib/Crypto++/include/Cryptopp/fltrimpl.h \
    lib/Crypto++/include/Cryptopp/gcm.h \
    lib/Crypto++/include/Cryptopp/gf256.h \
    lib/Crypto++/include/Cryptopp/gf2_32.h \
    lib/Crypto++/include/Cryptopp/gf2n.h \
    lib/Crypto++/include/Cryptopp/gfpcrypt.h \
    lib/Crypto++/include/Cryptopp/gost.h \
    lib/Crypto++/include/Cryptopp/gzip.h \
    lib/Crypto++/include/Cryptopp/hashfwd.h \
    lib/Crypto++/include/Cryptopp/hex.h \
    lib/Crypto++/include/Cryptopp/hkdf.h \
    lib/Crypto++/include/Cryptopp/hmac.h \
    lib/Crypto++/include/Cryptopp/hmqv.h \
    lib/Crypto++/include/Cryptopp/hrtimer.h \
    lib/Crypto++/include/Cryptopp/ida.h \
    lib/Crypto++/include/Cryptopp/idea.h \
    lib/Crypto++/include/Cryptopp/integer.h \
    lib/Crypto++/include/Cryptopp/iterhash.h \
    lib/Crypto++/include/Cryptopp/kalyna.h \
    lib/Crypto++/include/Cryptopp/keccak.h \
    lib/Crypto++/include/Cryptopp/lubyrack.h \
    lib/Crypto++/include/Cryptopp/luc.h \
    lib/Crypto++/include/Cryptopp/mars.h \
    lib/Crypto++/include/Cryptopp/md2.h \
    lib/Crypto++/include/Cryptopp/md4.h \
    lib/Crypto++/include/Cryptopp/md5.h \
    lib/Crypto++/include/Cryptopp/mdc.h \
    lib/Crypto++/include/Cryptopp/mersenne.h \
    lib/Crypto++/include/Cryptopp/misc.h \
    lib/Crypto++/include/Cryptopp/modarith.h \
    lib/Crypto++/include/Cryptopp/modes.h \
    lib/Crypto++/include/Cryptopp/modexppc.h \
    lib/Crypto++/include/Cryptopp/mqueue.h \
    lib/Crypto++/include/Cryptopp/mqv.h \
    lib/Crypto++/include/Cryptopp/naclite.h \
    lib/Crypto++/include/Cryptopp/nbtheory.h \
    lib/Crypto++/include/Cryptopp/network.h \
    lib/Crypto++/include/Cryptopp/nr.h \
    lib/Crypto++/include/Cryptopp/oaep.h \
    lib/Crypto++/include/Cryptopp/oids.h \
    lib/Crypto++/include/Cryptopp/osrng.h \
    lib/Crypto++/include/Cryptopp/ossig.h \
    lib/Crypto++/include/Cryptopp/padlkrng.h \
    lib/Crypto++/include/Cryptopp/panama.h \
    lib/Crypto++/include/Cryptopp/pch.h \
    lib/Crypto++/include/Cryptopp/pkcspad.h \
    lib/Crypto++/include/Cryptopp/poly1305.h \
    lib/Crypto++/include/Cryptopp/polynomi.h \
    lib/Crypto++/include/Cryptopp/ppc-simd.h \
    lib/Crypto++/include/Cryptopp/pssr.h \
    lib/Crypto++/include/Cryptopp/pubkey.h \
    lib/Crypto++/include/Cryptopp/pwdbased.h \
    lib/Crypto++/include/Cryptopp/queue.h \
    lib/Crypto++/include/Cryptopp/rabin.h \
    lib/Crypto++/include/Cryptopp/randpool.h \
    lib/Crypto++/include/Cryptopp/rc2.h \
    lib/Crypto++/include/Cryptopp/rc5.h \
    lib/Crypto++/include/Cryptopp/rc6.h \
    lib/Crypto++/include/Cryptopp/rdrand.h \
    lib/Crypto++/include/Cryptopp/resource.h \
    lib/Crypto++/include/Cryptopp/rijndael.h \
    lib/Crypto++/include/Cryptopp/ripemd.h \
    lib/Crypto++/include/Cryptopp/rng.h \
    lib/Crypto++/include/Cryptopp/rsa.h \
    lib/Crypto++/include/Cryptopp/rw.h \
    lib/Crypto++/include/Cryptopp/safer.h \
    lib/Crypto++/include/Cryptopp/salsa.h \
    lib/Crypto++/include/Cryptopp/scrypt.h \
    lib/Crypto++/include/Cryptopp/seal.h \
    lib/Crypto++/include/Cryptopp/secblock.h \
    lib/Crypto++/include/Cryptopp/seckey.h \
    lib/Crypto++/include/Cryptopp/seed.h \
    lib/Crypto++/include/Cryptopp/serpent.h \
    lib/Crypto++/include/Cryptopp/serpentp.h \
    lib/Crypto++/include/Cryptopp/sha.h \
    lib/Crypto++/include/Cryptopp/sha3.h \
    lib/Crypto++/include/Cryptopp/shacal2.h \
    lib/Crypto++/include/Cryptopp/shark.h \
    lib/Crypto++/include/Cryptopp/simon.h \
    lib/Crypto++/include/Cryptopp/simple.h \
    lib/Crypto++/include/Cryptopp/siphash.h \
    lib/Crypto++/include/Cryptopp/skipjack.h \
    lib/Crypto++/include/Cryptopp/sm3.h \
    lib/Crypto++/include/Cryptopp/sm4.h \
    lib/Crypto++/include/Cryptopp/smartptr.h \
    lib/Crypto++/include/Cryptopp/socketft.h \
    lib/Crypto++/include/Cryptopp/sosemanuk.h \
    lib/Crypto++/include/Cryptopp/speck.h \
    lib/Crypto++/include/Cryptopp/square.h \
    lib/Crypto++/include/Cryptopp/stdcpp.h \
    lib/Crypto++/include/Cryptopp/strciphr.h \
    lib/Crypto++/include/Cryptopp/tea.h \
    lib/Crypto++/include/Cryptopp/threefish.h \
    lib/Crypto++/include/Cryptopp/tiger.h \
    lib/Crypto++/include/Cryptopp/trap.h \
    lib/Crypto++/include/Cryptopp/trdlocal.h \
    lib/Crypto++/include/Cryptopp/trunhash.h \
    lib/Crypto++/include/Cryptopp/ttmac.h \
    lib/Crypto++/include/Cryptopp/tweetnacl.h \
    lib/Crypto++/include/Cryptopp/twofish.h \
    lib/Crypto++/include/Cryptopp/validate.h \
    lib/Crypto++/include/Cryptopp/vmac.h \
    lib/Crypto++/include/Cryptopp/wait.h \
    lib/Crypto++/include/Cryptopp/wake.h \
    lib/Crypto++/include/Cryptopp/whrlpool.h \
    lib/Crypto++/include/Cryptopp/winpipes.h \
    lib/Crypto++/include/Cryptopp/words.h \
    lib/Crypto++/include/Cryptopp/xtr.h \
    lib/Crypto++/include/Cryptopp/xtrcrypt.h \
    lib/Crypto++/include/Cryptopp/zdeflate.h \
    lib/Crypto++/include/Cryptopp/zinflate.h \
    lib/Crypto++/include/Cryptopp/zlib.h \
    lib/TinyXml/include/tinyxml/tinystr.h \
    lib/TinyXml/include/tinyxml/tinyxml.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bcon.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-atomic.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-clock.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-compat.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-config.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-context.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-decimal128.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-endian.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-error.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-iter.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-json.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-keys.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-macros.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-md5.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-memory.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-oid.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-reader.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-stdint.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-string.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-types.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-utf8.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-value.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-version-functions.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-version.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson-writer.h \
    lib/x2struct/thirdparty/libbson/include/libbson-1.0/bson.h \
    lib/x2struct/thirdparty/libconfig/include/libconfig.h++ \
    lib/x2struct/thirdparty/rapidjson/error/en.h \
    lib/x2struct/thirdparty/rapidjson/error/error.h \
    lib/x2struct/thirdparty/rapidjson/internal/biginteger.h \
    lib/x2struct/thirdparty/rapidjson/internal/diyfp.h \
    lib/x2struct/thirdparty/rapidjson/internal/dtoa.h \
    lib/x2struct/thirdparty/rapidjson/internal/ieee754.h \
    lib/x2struct/thirdparty/rapidjson/internal/itoa.h \
    lib/x2struct/thirdparty/rapidjson/internal/meta.h \
    lib/x2struct/thirdparty/rapidjson/internal/pow10.h \
    lib/x2struct/thirdparty/rapidjson/internal/regex.h \
    lib/x2struct/thirdparty/rapidjson/internal/stack.h \
    lib/x2struct/thirdparty/rapidjson/internal/strfunc.h \
    lib/x2struct/thirdparty/rapidjson/internal/strtod.h \
    lib/x2struct/thirdparty/rapidjson/internal/swap.h \
    lib/x2struct/thirdparty/rapidjson/msinttypes/inttypes.h \
    lib/x2struct/thirdparty/rapidjson/msinttypes/stdint.h \
    lib/x2struct/thirdparty/rapidjson/allocators.h \
    lib/x2struct/thirdparty/rapidjson/cursorstreamwrapper.h \
    lib/x2struct/thirdparty/rapidjson/document.h \
    lib/x2struct/thirdparty/rapidjson/encodedstream.h \
    lib/x2struct/thirdparty/rapidjson/encodings.h \
    lib/x2struct/thirdparty/rapidjson/filereadstream.h \
    lib/x2struct/thirdparty/rapidjson/filewritestream.h \
    lib/x2struct/thirdparty/rapidjson/fwd.h \
    lib/x2struct/thirdparty/rapidjson/istreamwrapper.h \
    lib/x2struct/thirdparty/rapidjson/memorybuffer.h \
    lib/x2struct/thirdparty/rapidjson/memorystream.h \
    lib/x2struct/thirdparty/rapidjson/ostreamwrapper.h \
    lib/x2struct/thirdparty/rapidjson/pointer.h \
    lib/x2struct/thirdparty/rapidjson/prettywriter.h \
    lib/x2struct/thirdparty/rapidjson/rapidjson.h \
    lib/x2struct/thirdparty/rapidjson/reader.h \
    lib/x2struct/thirdparty/rapidjson/schema.h \
    lib/x2struct/thirdparty/rapidjson/stream.h \
    lib/x2struct/thirdparty/rapidjson/stringbuffer.h \
    lib/x2struct/thirdparty/rapidjson/writer.h \
    lib/x2struct/thirdparty/rapidxml/rapidxml.hpp \
    lib/x2struct/thirdparty/rapidxml/rapidxml_iterators.hpp \
    lib/x2struct/thirdparty/rapidxml/rapidxml_print.hpp \
    lib/x2struct/thirdparty/rapidxml/rapidxml_utils.hpp \
    lib/x2struct/bson_builder.h \
    lib/x2struct/bson_reader.h \
    lib/x2struct/bson_writer.h \
    lib/x2struct/config.h \
    lib/x2struct/config_reader.h \
    lib/x2struct/config_writer.h \
    lib/x2struct/go_writer.h \
    lib/x2struct/json_reader.h \
    lib/x2struct/json_writer.h \
    lib/x2struct/rapidjson_custom.h \
    lib/x2struct/traits.h \
    lib/x2struct/util.h \
    lib/x2struct/x2struct.hpp \
    lib/x2struct/xml_reader.h \
    lib/x2struct/xml_writer.h \
    lib/x2struct/xreader.h \
    lib/x2struct/xstdint.h \
    lib/x2struct/xtypes.h

DISTFILES += \
    bin/debug/TestMyAlgorithm.pdb \
    bin/debug/TestMyAlgorithm.vc.pdb \
    lib/Crypto++/x64/cryptlib.lib \
    lib/Crypto++/x64/cryptlib_d.lib \
    lib/Crypto++/x86/cryptlib.lib \
    lib/Crypto++/x86/cryptlib_d.lib \
    lib/TinyXml/x64/tinyxml.lib \
    lib/TinyXml/x64/tinyxmld.lib \
    lib/TinyXml/x86/tinyxml.lib \
    lib/TinyXml/x86/tinyxmld.lib \
    lib/x2struct/thirdparty/libbson/lib/libbson-1.0.a \
    lib/x2struct/thirdparty/libconfig/lib/libconfig++.a \
    lib/x2struct/thirdparty/lnblade \
    lib/x2struct/thirdparty/rapidxml/manual.html \
    lib/x2struct/thirdparty/libbson/BUILD \
    lib/x2struct/thirdparty/libconfig/BUILD \
    lib/x2struct/thirdparty/rapidxml/license.txt
